-- CreateEnum
CREATE TYPE "VoiceType" AS ENUM ('UK_MALE', 'UK_FEMALE', 'US_MALE', 'US_FEMALE');

-- CreateEnum
CREATE TYPE "QuizQuestionType" AS ENUM ('MAIN_IDEA', 'DETAIL', 'INFERENCE', 'VOCABULARY', 'REFERENCE', 'PURPOSE_TONE', 'NOT_EXCEPT', 'SUMMARY');
