events { worker_connections 1024; }

http {
    gzip on;
    gzip_types text/plain application/json application/javascript text/css;

    limit_req_zone $binary_remote_addr zone=api:10m rate=30r/m;

    # HTTP → chuyển sang HTTPS
    server {
        listen 80;
        server_name api.miustore.io.vn;

        # Certbot challenge (lấy SSL)
        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }

    # HTTPS — NestJS
    server {
        listen 443 ssl;
        server_name api.miustore.io.vn;

        ssl_certificate     /etc/nginx/certs/live/api.miustore.io.vn/fullchain.pem;
        ssl_certificate_key /etc/nginx/certs/live/api.miustore.io.vn/privkey.pem;

        location / {
            limit_req zone=api burst=20 nodelay;
            proxy_pass http://app:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # WebSocket cho Socket.io
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}